version: 2.1

commands:
  run-tox:
    description: "Run tox"
    parameters:
      version:
        type: string
      sphinx-version:
        type: string
        default: "20,21,22,23,24,30,31,32,33,34,35,40,41,42,43,44,latest"
    steps:
      - checkout
      - run: pip install --user tox
      - run:
          command: tox -e "<<parameters.version>>-sphinx{<<parameters.sphinx-version>>}"

jobs:
  py37:
    docker:
      - image: 'cimg/python:3.7'
    steps:
      - run-tox:
          version: py37
  py38:
    docker:
      - image: 'cimg/python:3.8'
    steps:
      - run-tox:
          version: py38
  py39:
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - run-tox:
          version: py39
  py310:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - run-tox:
          version: py310
          sphinx-version: 42,43,44,latest
  checks:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - checkout
      - run: pip install --user tox
      - run: tox -e docs,lint

workflows:
  version: 2
  tests:
    jobs:
      - checks
      - py310
      - py39
      - py38
      - py37
